import {
  Card,
  CardMedia,
  CardContent,
  CardActions,
  Typography,
  Button,
  Grid,
} from "@material-ui/core";
import Head from "next/head";
import {Certificate, certificates} from '../models/certificate';
import Link from "next/link";
import { GetServerSideProps, NextPage } from "next";
import Navbar from '../components/Navbar';

//interface ProductsListPageProps {
 // products: Product[];
//}


const ProductsListPage = () => {
  return (
    <>
    <Navbar /> 
    <div>
      <Head>
        <title>Listagem de Certificados</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Typography component="h2" variant="h4" color="textPrimary" gutterBottom>
        Certificados
      </Typography>
      <Grid container spacing={4}>
        {certificates.map((certificate, key) => (
          <Grid key={key} item xs={12} sm={6} md={4}>
            <Card>
              <CardMedia
                style={{ paddingTop: "56%" }}
                image={certificate.image_url}
              />
              <CardContent>
                <Typography component="h3" variant="h5" gutterBottom>
                  {certificate.name}
                </Typography>
              </CardContent>
              <CardActions>
                <Link    href="/certificates/[slug]" >
                         
                  <Button size="small" color="primary" component="a">
                    Detalhes
                  </Button>
                </Link>
              </CardActions>
            </Card>
          </Grid>
        ))}
      </Grid>
    </div>
   </>
  );
};

export default ProductsListPage;

