export interface Certificate{
  id: string;
  name: string;
  description: string;
  author: string;
  image_url: string;
  slug: string;
  created_at: string;
}  

export const certificates: Certificate[] = [{
   id: "uuid",
   name: "Iniciativa Kubernetes ",
   description: "Varias tecnologias empregadast",
   author: "Wesley Willians",
   image_url: "./IniciativaKubernetes22.png",
   slug: "certificado-test",
   created_at: "2021-06-6T00:00:00",
},
{   id: "uuid",
   name: "Azure Devops ",
   description: "Deploy CI/CD com Azure Devops",
   author: "Wesley Willians",
   image_url: "./AzureDevops.png",
   slug: "certificado-2021",
   created_at: "2021-06-6T00:00:00",
},
{   id: "uuid",
   name: "Python para DataScience e Machine Lerarning",
   description: "Udemy - Curso de Marchine Learning",
   author: "Wesley Willians",
   image_url: "./python.png",
   slug: "certificado-2021",
   created_at: "2021-06-6T00:00:00",
},
{   id: "uuid",
   name: "React Native - Mobile",
   description: "Udemy - Curso de React Native",
   author: "Wesley Willians",
   image_url: "./reactnative.png",
   slug: "certificado-2021",
   created_at: "2021-06-6T00:00:00",
},
{   id: "uuid",
   name: "Selenium",
   description: "Deploy CI/CD com Azure Devops",
   author: "Wesley Willians",
   image_url: "./selenium.png",
   slug: "certificado-2021",
   created_at: "2021-06-6T00:00:00",
},
{   id: "uuid",
   name: "Dominios Ricos ",
   description: "Deploy CI/CD com Azure Devops",
   author: "Balta io",
   image_url: "./balta.png",
   slug: "certificado-2021",
   created_at: "2021-06-6T00:00:00",
},
{   id: "uuid",
   name: "Testes BDD",
   description: "Curso na QA Ninjas - Testes unitários com Selenium e apredizagem BDD (specflow)",
   author: "Wesley Willians",
   image_url: "./testeBDD.png",
   slug: "certificado-test",
   created_at: "2021-06-6T00:00:00",
},
{   id: "uuid",
   name: "Iniciativa Kubernetes ",
   description: "Varias tecnologias empregadas Kafka",
   author: "Wesley Willians",
   image_url: "./iniciativaKube21.png",
   slug: "certificado- 08/2021",
   created_at: "2021-06-6T00:00:00",
},
{   id: "uuid",
   name: "Contruindo Aplicação Escaláveis na Nuvem",
   description: "Trabalando com images, cache e Storage, gerando um container dela e Deploy no AzureDevps",
   author: "Wesley Willians",
   image_url: "./aplicescalavel.png",
   slug: "certificado-test",
   created_at: "2021-06-6T00:00:00",
},
{
   id: "uuid",
   name: "Rocketseat- DoWhile",
   description: "Várias tecnologias",
   author: "Diego Fernandes",
   image_url: "./Rocketseat.png",
   slug: "Rocketseat",
   created_at: "2021-06-6T00:00:00",
},

{   id: "uuid",
   name: "Boot Camp 2.0",
   description: "Varias tecnologias empregadas Kafka",
   author: "Wesley Willians",
   image_url: "./bootcamp2.png",
   slug: "certificado-test",
   created_at: "2021-06-6T00:00:00",
},

];



